name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        env:
          super: ${{ secrets.SECRET_KEY }}

      # Deploy
      run: rsync -e "ssh -p 20022 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . /var/www/baldcatdev/mnimi.baldcatdev.com/test_for_mirohost
